<?php

namespace Database\Seeders;

use App\Models\NumberSeries;
use Illuminate\Database\Seeder;

/**
 * One counter per module that generates its own codes.
 *
 * firstOrCreate on (module, financial_year) — re-running must never reset
 * current_number, or the next save hands out a code that already exists.
 *
 * Category is the one master whose sheet itself says "autogenerated".
 * Product, Supplier and Agent codes are still typed by the user with a
 * duplicate check, per their sheets. Buyer's sheet said "typed" too, but the
 * client has since asked for BUY01-style auto-generated codes instead — see
 * BuyerService::create().
 */
class NumberSeriesSeeder extends Seeder
{
    public function run(): void
    {
        $series = [
            [
                'module'         => 'category',
                'prefix'         => 'CAT',
                'financial_year' => null,   // CAT001 does not restart each year
                'padding'        => 3,
                'reset_yearly'   => false,
            ],
            [
                'module'         => 'buyer',
                'prefix'         => 'BUY',
                'financial_year' => null,   // BUY01 does not restart each year
                'padding'        => 2,      // BUY + 2 digits = 5 chars, the sheet's own max length
                'reset_yearly'   => false,
            ],
        ];

        // inward-entry is financial-year-scoped (GT/INW/xxx/<FY>) and its rows
        // are created on demand by InwardEntryService::ensureNumberSeries() —
        // seeding a financial_year-less row here would just be a dead entry
        // the lookup (keyed on module + financial_year) never matches.

        foreach ($series as $row) {
            NumberSeries::firstOrCreate(
                ['module' => $row['module'], 'financial_year' => $row['financial_year']],
                $row
            );
        }

        $this->command?->info('Number series seeded.');
    }
}
