<?php

namespace App\Services;

use App\Models\NumberSeries;
use Illuminate\Support\Facades\DB;
use RuntimeException;

/**
 * Hands out the next display code for a module — CAT001, CAT002, …
 *
 * Category sheet column A says "autogenerated". Everything that is
 * autogenerated comes through here rather than through max(id) + 1, because
 * codes have to survive deletes: if CAT003 is deleted, the next category is
 * CAT004, not CAT003 again pointing at different data in someone's old PDF.
 */
class NumberSeriesService
{
    /**
     * Reserve and return the next code for a module.
     *
     * Must be called inside the same transaction as the insert that uses the
     * code. lockForUpdate() holds the row until that transaction commits, so
     * two users saving at the same moment queue instead of both reading the
     * same current_number and both writing CAT005.
     */
    public function next(string $module, ?string $financialYear = null): string
    {
        return DB::transaction(function () use ($module, $financialYear) {
            $series = NumberSeries::query()
                ->where('module', $module)
                ->where('financial_year', $financialYear)
                ->lockForUpdate()
                ->first();

            if (! $series) {
                throw new RuntimeException(
                    "No number series configured for module [{$module}]. Run NumberSeriesSeeder."
                );
            }

            $series->increment('current_number');

            return $this->format($series);
        });
    }

    /**
     * What the next code would be, without consuming it.
     *
     * Used to show a read-only preview on the create form. The value shown is
     * not reserved — if someone else saves first, the code actually assigned on
     * submit is the next one. That is why the form field is read-only and the
     * real code is assigned server-side at insert time, not carried in the
     * request.
     */
    public function preview(string $module, ?string $financialYear = null): ?string
    {
        $series = NumberSeries::query()
            ->where('module', $module)
            ->where('financial_year', $financialYear)
            ->first();

        if (! $series) {
            return null;
        }

        $series->current_number++;

        return $this->format($series);
    }

    private function format(NumberSeries $series): string
    {
        $number = str_pad((string) $series->current_number, $series->padding, '0', STR_PAD_LEFT);

        return $series->financial_year
            ? "{$series->prefix}{$series->financial_year}/{$number}"
            : "{$series->prefix}{$number}";
    }
}
