@props([
    'buyer' => null,
    'categories' => [],
    'agents' => [],
    'countries' => [],
    // Rendered server-side for the country/state already chosen; the cascade
    // reloads them from GeoController once a parent changes.
    'states' => [],
    'cities' => [],
    'ports' => [],
    'paymentTerms' => [],
    'incoterms' => [],
    'shipmentMethods' => [],
    'currencies' => [],
])

@php
    use App\Models\Buyer;

    /**
     * Buyer form — every field here is a column on the client's Buyer Master
     * sheet, in the sheet's own order. Nothing has been added.
     *
     * Laid out one field per line, label on the left, grouped into sections —
     * same as the Category and Product masters. 26 columns in a flat grid is
     * unreadable.
     *
     * "GST/VAT No" (sheet col H) is deliberately not rendered: the sheet marks
     * it "not required" and highlights it. The column exists and stays nullable
     * so it can be switched on later without a migration.
     */

    // Categories already linked, for the multi-select.
    $selectedCategories = $buyer?->categories->pluck('id')->all() ?? [];

    /**
     * Carton mark rows to render (sheet col X).
     *
     * On an edit, whatever was saved. On a new buyer — or on a buyer saved
     * before any marks were entered — the five lines the sheet draws, as a
     * starting point. Labels stay editable either way.
     */
    $cartonLines = old('carton_markings');

    if ($cartonLines === null) {
        $cartonLines = $buyer?->cartonMarkings->isNotEmpty()
            ? $buyer->cartonMarkings->map(fn ($line) => [
                'label' => $line->label,
                'value' => $line->value,
            ])->all()
            : collect(Buyer::DEFAULT_CARTON_LINES)
                ->map(fn ($line) => ['label' => $line['label'], 'value' => null])
                ->all();
    }

    $cartonPlaceholders = collect(Buyer::DEFAULT_CARTON_LINES)->pluck('placeholder')->all();
@endphp

{{-- ===================== A–D · IDENTIFICATION ===================== --}}
<x-ui.form-section title="Identification" icon="bi-globe-asia-australia"
                   subtitle="Who the buyer is, here and on the export invoice.">
    <div class="form-stack">

        {{-- Col A — "max 5 characters. it should tell me if a certain code is
             used already". Typed, not autogenerated: Category and Product get a
             CAT001 from the number series, this one the user chooses. --}}
        <div class="row form-line">
            <label for="display_code" class="col-sm-4 col-lg-3 col-form-label fw-semibold">
                Display Code <span class="req">*</span>
            </label>
            <div class="col-sm-8 col-lg-9">
                <div class="input-group">
                    <span class="input-group-text bg-body-secondary"><i class="bi bi-hash"></i></span>
                    <input type="text" id="display_code" name="display_code" maxlength="5" required
                           value="{{ old('display_code', $buyer?->display_code) }}"
                           class="form-control font-monospace text-uppercase js-code-check @error('display_code') is-invalid @enderror"
                           placeholder="BUY01" autocomplete="off">
                </div>
                @error('display_code')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                {{-- Written by JS only once a code has actually been checked. --}}
                <div class="form-text js-code-feedback">Up to 5 characters. Must be unique.</div>
            </div>
        </div>

        {{-- Col B --}}
        <x-ui.field name="company_name" label="Company Name" :value="$buyer?->company_name" required
                    horizontal maxlength="200" placeholder="ABC Fashion Ltd" />

        {{-- Col C — the legal name on the invoice is not always the trading name --}}
        <x-ui.field name="name_on_export_invoice" label="Name on Export Invoice"
                    :value="$buyer?->name_on_export_invoice" horizontal maxlength="200"
                    placeholder="Exactly as it must print on the invoice"
                    hint="Leave blank to use the company name." />

        {{-- Col D — "allow multiple selection in a drop down menu which is
             connected from the category master" --}}
        <x-ui.select name="category_ids" label="Category of Items"
                     :options="$categories" :selected="$selectedCategories"
                     horizontal searchable multiple
                     placeholder="Search categories…"
                     hint="Pick every category this buyer orders." />

    </div>
</x-ui.form-section>

{{-- ======================= E–G · CONTACT ========================== --}}
<x-ui.form-section title="Contact" icon="bi-person-lines-fill">
    <div class="form-stack">

        {{-- Col E --}}
        <x-ui.field name="contact_person" label="Contact Person" :value="$buyer?->contact_person"
                    horizontal maxlength="120" placeholder="John Smith" />

        {{-- Col F --}}
        <x-ui.field name="email" label="Email" type="email" :value="$buyer?->email"
                    horizontal maxlength="150" placeholder="john@abcfashion.com" />

        {{-- Col G --}}
        <x-ui.field name="mobile" label="Mobile" :value="$buyer?->mobile"
                    horizontal maxlength="30" placeholder="+44 987654321" />

    </div>
</x-ui.form-section>

{{-- ==================== I–N · ADDRESS & PORT ====================== --}}
<x-ui.form-section title="Address & Destination" icon="bi-geo-alt"
                   subtitle="Prints on the export invoice and the packing list.">
    <div class="form-stack">

        {{-- Col I --}}
        <x-ui.textarea name="address" label="Address" :value="$buyer?->address"
                       horizontal rows="2" maxlength="255" placeholder="12 Fashion Street" />

        {{-- Cols L, K, J — Country, State, City.

             Ordered parent-first, which is the reverse of the sheet's own
             J, K, L. A dependent dropdown that sits above the field it depends
             on reads as broken: the user tabs into "City", finds it empty, and
             has no way to tell that the answer is three rows further down.

             The three cascade. State lists only states in the chosen country,
             City only cities in the chosen state, and both are re-checked
             against their parent on submit — see BuyerRequest. --}}
        <x-ui.select name="country_id" label="Country" :options="$countries"
                     :selected="$buyer?->country_id" horizontal searchable
                     placeholder="Search country…"
                     data-cascade-child="#state_id" />

        {{-- Col K --}}
        <x-ui.select name="state_id" label="State" :options="$states"
                     :selected="$buyer?->state_id" horizontal searchable
                     placeholder="Search state…"
                     data-cascade-child="#city_id"
                     data-cascade-parent="#country_id"
                     :data-cascade-url="route('masters.geo.states')"
                     data-cascade-key="country_id"
                     data-cascade-empty="Select a country first" />

        {{-- Col J --}}
        <x-ui.select name="city_id" label="City" :options="$cities"
                     :selected="$buyer?->city_id" horizontal searchable
                     placeholder="Search city…"
                     data-cascade-parent="#state_id"
                     :data-cascade-url="route('masters.geo.cities')"
                     data-cascade-key="state_id"
                     data-cascade-empty="Select a state first" />

        {{-- Col M --}}
        <x-ui.field name="pincode" label="PIN / ZIP Code" :value="$buyer?->pincode"
                    horizontal maxlength="20" placeholder="EC1A1AA" />

        {{-- Col N — same reasoning as Country --}}
        <x-ui.select name="port_id" label="Destination Port" :options="$ports"
                     :selected="$buyer?->port_id" horizontal searchable
                     placeholder="Search port…" />

    </div>
</x-ui.form-section>

{{-- ====================== O–P · AGENT ============================= --}}
<x-ui.form-section title="Agent" icon="bi-person-badge"
                   subtitle="Optional — only agents marked as buyer-side are listed.">
    <div class="form-stack">

        {{-- Col O — "only those which are a part of buyer side selected in
             agent master should show here". The list is filtered by the
             controller and the same rule is re-checked on submit. --}}
        <x-ui.select name="agent_id" label="Agent" :options="$agents"
                     :selected="$buyer?->agent_id" horizontal searchable
                     placeholder="Search agent…"
                     :hint="count($agents) ? null : 'No buyer-side agents exist yet.'" />

        {{-- Col P. Type and value are separate columns so settlement maths never
             parses a label — '2%' and '2 USD per piece' cannot both come out of
             one text field. --}}
        <div class="row form-line">
            <label for="agent_commission_value" class="col-sm-4 col-lg-3 col-form-label fw-semibold">
                Agent Commission
            </label>
            <div class="col-sm-8 col-lg-9">
                <div class="input-group">
                    <input type="number" step="0.0001" min="0"
                           id="agent_commission_value" name="agent_commission_value"
                           value="{{ old('agent_commission_value', $buyer?->agent_commission_value) }}"
                           class="form-control @error('agent_commission_value') is-invalid @enderror"
                           placeholder="0.0000">
                    <select name="agent_commission_type" style="max-width:140px"
                            class="form-select @error('agent_commission_type') is-invalid @enderror">
                        @foreach(['percent' => '% Percent', 'amount' => 'Fixed amount'] as $value => $text)
                            <option value="{{ $value }}"
                                @selected(old('agent_commission_type', $buyer?->agent_commission_type) === $value)>{{ $text }}</option>
                        @endforeach
                    </select>
                </div>
                @error('agent_commission_value')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                @error('agent_commission_type')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                <div class="form-text">
                    This buyer's rate for this agent. The same agent can carry a different rate for another buyer.
                </div>
            </div>
        </div>

    </div>
</x-ui.form-section>

{{-- =================== Q–T · TRADE TERMS ========================== --}}
<x-ui.form-section title="Trade Terms" icon="bi-file-earmark-text"
                   subtitle="Defaults copied onto this buyer's quotations and order confirmations.">
    <div class="form-stack">

        {{-- Col Q --}}
        <x-ui.select name="payment_term_id" label="Payment Terms" :options="$paymentTerms"
                     :selected="$buyer?->payment_term_id" horizontal searchable
                     placeholder="Search terms…" />

        {{-- Col R --}}
        <x-ui.select name="incoterm_id" label="Inco Terms" :options="$incoterms"
                     :selected="$buyer?->incoterm_id" horizontal searchable
                     placeholder="Search incoterm…" />

        {{-- Col S --}}
        <x-ui.select name="shipment_method_id" label="Shipment Method" :options="$shipmentMethods"
                     :selected="$buyer?->shipment_method_id" horizontal searchable
                     placeholder="Search method…" />

        {{-- Col T --}}
        <x-ui.select name="currency_id" label="Currency of Payment" :options="$currencies"
                     :selected="$buyer?->currency_id" horizontal searchable
                     placeholder="Search currency…" />

    </div>
</x-ui.form-section>

{{-- ===================== U–W · BANK DETAILS ======================= --}}
<x-ui.form-section title="Bank Details" icon="bi-bank"
                   subtitle="Where this buyer remits payment from.">
    <div class="form-stack">

        {{-- Col U --}}
        <x-ui.field name="bank_name" label="Bank Name" :value="$buyer?->bank_name"
                    horizontal maxlength="120" placeholder="HSBC UK" />

        {{-- Col V --}}
        <x-ui.field name="account_number" label="Account Number" :value="$buyer?->account_number"
                    horizontal maxlength="40" placeholder="12345678" />

        {{-- Col W --}}
        <x-ui.field name="swift_code" label="SWIFT Code" :value="$buyer?->swift_code"
                    horizontal maxlength="20" placeholder="HBUKGB4B"
                    class="text-uppercase" />

    </div>
</x-ui.form-section>

{{-- ================== X · CARTON MARKING DETAILS ================== --}}
<x-ui.form-section title="Carton Marking Details" icon="bi-box-seam"
                   subtitle="Enter each line as it should appear on the carton / shipping marks.">
    <div class="row g-4">
        <div class="col-lg-7">
            <div id="carton-lines">
                @foreach($cartonLines as $index => $line)
                    <div class="carton-line" data-carton-line>
                        <div class="carton-line-head">
                            <input type="text" maxlength="60"
                                   name="carton_markings[{{ $index }}][label]"
                                   value="{{ $line['label'] ?? '' }}"
                                   class="carton-label-input" placeholder="LINE LABEL"
                                   aria-label="Line label">
                            <button type="button" class="btn btn-sm btn-link text-danger p-0 js-remove-line"
                                    aria-label="Remove line" data-bs-toggle="tooltip" title="Remove line">
                                <i class="bi bi-x-lg"></i>
                            </button>
                        </div>
                        <input type="text" maxlength="120"
                               name="carton_markings[{{ $index }}][value]"
                               value="{{ $line['value'] ?? '' }}"
                               class="form-control js-carton-value"
                               placeholder="{{ $cartonPlaceholders[$index] ?? 'e.g. MADE IN INDIA' }}"
                               aria-label="Line value">
                        @error("carton_markings.{$index}.value")
                            <div class="invalid-feedback d-block">{{ $message }}</div>
                        @enderror
                    </div>
                @endforeach
            </div>

            <button type="button" class="btn btn-sm btn-outline-secondary mt-2" id="add-carton-line">
                <i class="bi bi-plus-lg me-1"></i>Add line
            </button>
            <div class="form-text">
                Blank lines are not saved. Drag is not supported — use Add line and retype to reorder.
            </div>
        </div>

        {{-- The sheet shows a live preview beside the inputs. It is display
             only; what saves is the inputs. --}}
        <div class="col-lg-5">
            <div class="carton-preview">
                <div class="carton-preview-head">Live preview</div>
                <pre id="carton-preview-body" class="carton-preview-body mb-0"></pre>
            </div>
        </div>
    </div>
</x-ui.form-section>

{{-- ======================= Y, Z · OTHER =========================== --}}
<x-ui.form-section title="Other Details" icon="bi-card-text">
    <div class="form-stack">

        {{-- Col Z --}}
        <x-ui.select name="status" label="Status" required horizontal
                     :options="['active' => 'Active', 'inactive' => 'Inactive']"
                     :selected="$buyer?->status ?? 'active'"
                     :placeholder="false" />

        {{-- Col Y --}}
        <x-ui.textarea name="remarks" label="Remarks" :value="$buyer?->remarks"
                       horizontal rows="2" placeholder="Optional notes" />

    </div>
</x-ui.form-section>

<div class="form-actions">
    <button type="submit" class="btn btn-primary px-4">
        <i class="bi bi-check-lg me-1"></i>{{ $buyer ? 'Update' : 'Save' }} Buyer
    </button>
    <a href="{{ route('masters.buyers.index') }}" class="btn btn-outline-secondary">Cancel</a>
</div>

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function () {

    /* ------------------------------------------------------------------ *
     * Carton marking details (sheet col X) — repeatable lines with a live
     * preview. The preview is display only; the inputs are what save.
     * ------------------------------------------------------------------ */
    const lineWrap = document.getElementById('carton-lines');
    const preview  = document.getElementById('carton-preview-body');

    function renderPreview() {
        const lines = Array.from(lineWrap.querySelectorAll('.js-carton-value'))
            .map(input => input.value.trim())
            .filter(Boolean);

        preview.textContent = lines.length ? lines.join('\n') : 'Nothing entered yet.';
        preview.classList.toggle('is-empty', lines.length === 0);
    }

    /**
     * Field names carry their row index, so a row added after one was removed
     * must not reuse an index still in the DOM — two inputs sharing
     * carton_markings[2][value] would silently drop one on submit.
     */
    function reindex() {
        lineWrap.querySelectorAll('[data-carton-line]').forEach(function (row, index) {
            row.querySelectorAll('input[name^="carton_markings"]').forEach(function (input) {
                input.name = input.name.replace(/carton_markings\[\d+\]/, 'carton_markings[' + index + ']');
            });
        });
    }

    lineWrap.addEventListener('input', function (event) {
        if (event.target.classList.contains('js-carton-value')) renderPreview();
    });

    lineWrap.addEventListener('click', function (event) {
        const remove = event.target.closest('.js-remove-line');
        if (! remove) return;

        // Keep at least one row — an empty container has no "add" affordance
        // beyond the button, and clearing the last row is the same outcome.
        const rows = lineWrap.querySelectorAll('[data-carton-line]');
        if (rows.length === 1) {
            rows[0].querySelectorAll('input').forEach(input => input.value = '');
        } else {
            remove.closest('[data-carton-line]').remove();
        }

        reindex();
        renderPreview();
    });

    document.getElementById('add-carton-line').addEventListener('click', function () {
        const index = lineWrap.querySelectorAll('[data-carton-line]').length;
        const row = document.createElement('div');

        row.className = 'carton-line';
        row.setAttribute('data-carton-line', '');
        row.innerHTML =
            '<div class="carton-line-head">' +
                '<input type="text" maxlength="60" class="carton-label-input" ' +
                       'name="carton_markings[' + index + '][label]" placeholder="LINE LABEL" aria-label="Line label">' +
                '<button type="button" class="btn btn-sm btn-link text-danger p-0 js-remove-line" aria-label="Remove line">' +
                    '<i class="bi bi-x-lg"></i>' +
                '</button>' +
            '</div>' +
            '<input type="text" maxlength="120" class="form-control js-carton-value" ' +
                   'name="carton_markings[' + index + '][value]" placeholder="e.g. GROSS WT:" aria-label="Line value">';

        lineWrap.appendChild(row);
        row.querySelector('.carton-label-input').focus();
    });

    renderPreview();

    /* ------------------------------------------------------------------ *
     * "Tell me if a certain code is used already" (sheet col A).
     * A convenience only — the unique index is what actually enforces it.
     * ------------------------------------------------------------------ */
    const input    = document.getElementById('display_code');
    const feedback = document.querySelector('.js-code-feedback');
    const checkUrl = @json(route('masters.buyers.check-code'));
    const ignoreId = @json($buyer?->id);
    const original = input.value.trim().toUpperCase();
    const resting  = feedback.textContent;
    let timer = null;

    function rest() {
        feedback.textContent = resting;
        feedback.className = 'form-text js-code-feedback';
    }

    input.addEventListener('input', function () {
        clearTimeout(timer);
        const value = input.value.trim().toUpperCase();

        // Unchanged on an edit form is not a clash with itself.
        if (value === '' || value === original) {
            input.classList.remove('is-invalid', 'is-valid');
            rest();
            return;
        }

        // Debounced so a 5-character code is one request, not five.
        timer = setTimeout(function () {
            const params = new URLSearchParams({ value: value });
            if (ignoreId) params.append('ignore', ignoreId);

            fetch(checkUrl + '?' + params, { headers: { 'Accept': 'application/json' } })
                .then(r => r.ok ? r.json() : Promise.reject())
                .then(function (data) {
                    input.classList.toggle('is-invalid', !data.available);
                    input.classList.toggle('is-valid', data.available);
                    feedback.textContent = data.available
                        ? 'Available.'
                        : 'Already used by another buyer — choose another.';
                    feedback.className = 'form-text js-code-feedback ' +
                        (data.available ? 'text-success' : 'text-danger');
                })
                // Network failure must not block the form. The unique index
                // still rejects a duplicate on submit.
                .catch(rest);
        }, 350);
    });
});
</script>
@endpush
