<?php

namespace App\Http\Requests\Masters;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreCategoryRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user()->can('category.create');
    }

    /**
     * The code is not here on purpose. It is autogenerated server-side
     * (sheet col A) and the form field is read-only, so accepting it from the
     * request would let a crafted POST choose its own code.
     *
     * Uniqueness deliberately does NOT exclude soft-deleted rows: the database
     * index does not either, so excluding them here would let validation pass
     * and the insert then fail with a duplicate-key error. A deleted category
     * keeps its name reserved — restore it rather than retyping it.
     *
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            'name'        => ['required', 'string', 'max:120', Rule::unique('categories', 'name')],

            // Several formats, not one — see the 000300 category_format
            // migration. Optional: a category can be created before anyone has
            // decided which order formats belong under it.
            'format_ids'   => ['nullable', 'array'],
            'format_ids.*' => ['integer', Rule::exists('document_formats', 'id')],

            'status'      => ['required', Rule::in(['active', 'inactive'])],
            'remarks'     => ['nullable', 'string', 'max:1000'],
        ];
    }

    /**
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'name.unique' => 'A category with this name already exists.',
        ];
    }
}
