@props(['category' => null, 'poFormats' => [], 'nextCode' => null])

{{--
    Category form — every field here is a column on the client's Category Master
    sheet. Nothing has been added.

    Laid out one field per line, label on the left. The sheet has six columns and
    reads top to bottom; a multi-column grid made the eye jump around for no gain.

    "Description" (sheet col C) is deliberately not rendered: the sheet marks it
    "not needed". The column exists and stays nullable so it can be switched on
    later without a migration.
--}}

<x-ui.form-section title="Category Details" icon="bi-tags"
                   subtitle="Products, jobbers and suppliers are all linked to a category.">
    <div class="form-stack">

        {{-- Col A: autogenerated. Read-only and not submitted — the code is
             assigned server-side at insert, so this is a preview, not a
             reservation. If someone else saves first, the next one is used. --}}
        <div class="row form-line">
            <label class="col-sm-4 col-lg-3 col-form-label fw-semibold">Category Code</label>
            <div class="col-sm-8 col-lg-9">
                <div class="input-group">
                    <span class="input-group-text bg-body-secondary"><i class="bi bi-hash"></i></span>
                    <input type="text" class="form-control font-monospace"
                           value="{{ $category?->code ?? $nextCode ?? 'Auto' }}" readonly>
                </div>
                <div class="form-text">
                    {{ $category
                        ? 'Codes never change — they appear on documents already sent.'
                        : 'Assigned automatically when you save.' }}
                </div>
            </div>
        </div>

        {{-- Col B --}}
        <x-ui.field name="name" label="Category Name" :value="$category?->name" required
                    horizontal placeholder="Men's Shirts" />

        {{-- Col F: "drop down with search bar to look for particular formats" --}}
        <x-ui.select name="po_format_id" label="PO Format Linked"
                     :options="$poFormats" :selected="$category?->po_format_id"
                     horizontal searchable placeholder="Search format…" />

        {{-- Col D --}}
        <x-ui.select name="status" label="Status" required horizontal
                     :options="['active' => 'Active', 'inactive' => 'Inactive']"
                     :selected="$category?->status ?? 'active'"
                     :placeholder="false" />

        {{-- Col E --}}
        <x-ui.textarea name="remarks" label="Remarks" :value="$category?->remarks"
                       horizontal rows="2" placeholder="Optional notes" />

    </div>
</x-ui.form-section>

<div class="form-actions">
    <button type="submit" class="btn btn-primary px-4">
        <i class="bi bi-check-lg me-1"></i>{{ $category ? 'Update' : 'Save' }} Category
    </button>
    <a href="{{ route('masters.categories.index') }}" class="btn btn-outline-secondary">Cancel</a>
</div>
