<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Category master — Category Master sheet.
 *
 * | Sheet col | Field             | Sheet note                                          |
 * |-----------|-------------------|-----------------------------------------------------|
 * | A         | Category Code     | "autogenerated"          -> CAT001 via number series |
 * | B         | Category Name     | "text box to type"                                  |
 * | C         | Description       | "not needed"             -> column kept, off the form|
 * | D         | Status            | "drop down to choose"                               |
 * | E         | Remarks           | "text box to type"                                  |
 * | F         | Po format linked  | "drop down with search bar to look for particular formats" |
 *
 * Description is marked "not needed" on the sheet and is struck through in red.
 * The column stays nullable rather than being dropped: it costs nothing, and
 * re-adding it later once data exists is a migration plus a backfill. It is
 * simply not rendered on the form.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('categories', function (Blueprint $table) {
            $table->id();
            $table->string('code', 20)->unique();     // CAT001 — assigned by NumberSeriesService
            $table->string('name', 120)->unique();    // "it should tell me if a certain code is used already"
            $table->text('description')->nullable();  // sheet: "not needed"
            $table->foreignId('po_format_id')->nullable()->constrained('document_formats')->nullOnDelete();
            $table->enum('status', ['active', 'inactive'])->default('active');
            $table->text('remarks')->nullable();

            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();
            $table->softDeletes();

            $table->index('status');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('categories');
    }
};
