<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Buyer master — Buyer Master sheet, DATABASE_SCHEMA.md §4.
 *
 * | Col | Field                        | Sheet note                                                        |
 * |-----|------------------------------|-------------------------------------------------------------------|
 * | A   | display code                 | "max 5 characters, tell me if a certain code is used already"      |
 * | B   | Company Name                 | textbox                                                           |
 * | C   | company name on export invoice | textbox                                                         |
 * | D   | category of items            | "multiple selection in a drop down connected from category master" |
 * | E   | Contact Person               | text box                                                          |
 * | F   | Email                        | textbox                                                           |
 * | G   | Mobile                       | textbox                                                           |
 * | H   | GST/VAT No                   | "not required"  -> column kept, off the form                      |
 * | I–M | Address, City, State, Country, PIN Code | text boxes                                             |
 * | N   | Port                         | text box on the sheet -> FK, see below                            |
 * | O   | Agent                        | "only those which are a part of buyer side" — filtered dropdown   |
 * | P   | agent commission             | header only, no widget note                                       |
 * | Q   | Payment Terms                | drop down menu                                                    |
 * | R   | inco terms                   | drop down with search bar, choice to add more                     |
 * | S   | shipment methods             | drop down, add more in the future                                 |
 * | T   | currency of payment          | drop down, add more in the future                                 |
 * | U–W | bank name, account number, swift code | textboxes                                                |
 * | X   | carton marking details       | 5-line widget with live preview -> buyer_carton_markings          |
 * | Y   | Remarks                      | text box                                                          |
 * | Z   | Status                       | drop down with options to choose                                  |
 *
 * Two deliberate departures from the sheet's own annotations:
 *
 * 1. `display_code` is typed, not autogenerated. The sheet asks for a duplicate
 *    warning, which only makes sense for a code the user chooses. Category and
 *    Product go the other way (CAT001 from NumberSeriesService) — that is the
 *    sheet's instruction on those tabs, not an inconsistency here.
 *
 * 2. Country and Port are foreign keys although the sheet draws them as text
 *    boxes. §0a's rule is "manual entry at master level, dropdowns after", but
 *    a buyer's country and destination port are consumed by export documents,
 *    where "UK" / "U.K." / "United Kingdom" typed across three buyers becomes
 *    three countries on three invoices. City and State stay free text — nothing
 *    downstream filters or totals on those.
 *
 * `gst_vat_no` is marked "not required" and highlighted on the sheet. Kept
 * nullable and off the form, same treatment as categories.description — the
 * column costs nothing, and re-adding it after data exists is a migration plus
 * a backfill.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('buyers', function (Blueprint $table) {
            $table->id();

            // Col A. Unique index is what actually enforces the "already used"
            // rule; the live check on the form is a convenience on top of it.
            $table->string('display_code', 5)->unique();

            // Cols B, C
            $table->string('company_name', 200);
            $table->string('name_on_export_invoice', 200)->nullable();

            // Cols E, F, G
            $table->string('contact_person', 120)->nullable();
            $table->string('email', 150)->nullable();
            $table->string('mobile', 30)->nullable();

            // Col H — sheet: "not required"
            $table->string('gst_vat_no', 30)->nullable();

            // Cols I–N
            $table->string('address', 255)->nullable();
            $table->string('city', 80)->nullable();
            $table->string('state', 80)->nullable();
            $table->foreignId('country_id')->nullable()->constrained()->nullOnDelete();
            $table->string('pincode', 20)->nullable();
            $table->foreignId('port_id')->nullable()->constrained()->nullOnDelete();

            // Col O — nullable: "not necessarily, but I need it as an option".
            $table->foreignId('agent_id')->nullable()->constrained()->nullOnDelete();

            /*
             * Col P. Split into type + value rather than one string, because
             * this feeds the Agent Commission screen in Accounts — "2%" and
             * "2 USD per piece" cannot both be parsed out of one text column at
             * settlement time.
             */
            $table->enum('agent_commission_type', ['percent', 'amount'])->nullable();
            $table->decimal('agent_commission_value', 12, 4)->nullable();

            // Cols Q–T
            $table->foreignId('payment_term_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('incoterm_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('shipment_method_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('currency_id')->nullable()->constrained()->nullOnDelete();

            // Cols U–W
            $table->string('bank_name', 120)->nullable();
            $table->string('account_number', 40)->nullable();
            $table->string('swift_code', 20)->nullable();

            // Cols Y, Z
            $table->enum('status', ['active', 'inactive'])->default('active');
            $table->text('remarks')->nullable();

            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();
            $table->softDeletes();

            $table->index('status');
            $table->index('company_name');
        });

        /*
         * Col D: "allow multiple selection in a drop down menu which is
         * connected from the category master".
         *
         * restrictOnDelete on category_id, matching products: a category in use
         * by a buyer cannot be deleted out from under it. CategoryService
         * already blocks the product case with a readable message; the buyer
         * case is added there too.
         */
        Schema::create('buyer_category', function (Blueprint $table) {
            $table->id();
            $table->foreignId('buyer_id')->constrained()->cascadeOnDelete();
            $table->foreignId('category_id')->constrained()->restrictOnDelete();

            $table->unique(['buyer_id', 'category_id']);
        });

        /*
         * Col X. The sheet draws five fixed lines (BUYER NAME / DESTINATION /
         * ORDER REF / MADE IN INDIA / GROSS WT) with a live preview, the first
         * three starred as required.
         *
         * Rows rather than five columns on `buyers`, because the same sheet
         * says "choice to add more too" elsewhere and a sixth line would
         * otherwise be a migration. `line_no` carries the print order — the
         * marks have to come out of the database in the order they appear on
         * the carton.
         */
        Schema::create('buyer_carton_markings', function (Blueprint $table) {
            $table->id();
            $table->foreignId('buyer_id')->constrained()->cascadeOnDelete();
            $table->tinyInteger('line_no')->unsigned();
            $table->string('label', 60);                    // "BUYER NAME"
            $table->string('value', 120)->nullable();       // "abc corp"
            $table->boolean('is_required')->default(false);
            $table->timestamps();

            $table->unique(['buyer_id', 'line_no']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('buyer_carton_markings');
        Schema::dropIfExists('buyer_category');
        Schema::dropIfExists('buyers');
    }
};
