<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Agent master — Agent Master sheet, DATABASE_SCHEMA.md §2.
 *
 * Built here because the Buyer master needs it: Buyer sheet col O is
 * "drop down based on connection from agent master with a search bar — only
 * those which are a part of buyer side selected in agent master should show
 * here". That filter is not cosmetic, so the tables backing it have to be real.
 *
 * The same precedent as `document_formats` in 000100 applies: the Agent Master
 * *screen* is a later phase, but the table exists now so `buyers.agent_id` is a
 * genuine foreign key rather than a loose integer that has to be migrated again
 * once the screen is built.
 *
 * `display_code` is typed by the user, NOT autogenerated. The sheet says "max 5
 * characters, it should tell me if a certain code is used already" — the same
 * rule as Buyer and Supplier, and the opposite of Category/Product, which get a
 * CAT001 from NumberSeriesService.
 *
 * There is deliberately no commission *value* column here. Buyer col P and
 * Supplier col Y are both "agent commission", so one agent carries 2% for one
 * buyer and 3% for another. `agents` holds who and how it is measured; the
 * party tables hold how much.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('agents', function (Blueprint $table) {
            $table->id();
            $table->string('display_code', 5)->unique();   // sheet: max 5 chars, typed
            $table->string('name', 150);

            // Sheet col E — headed "commission basis" with no options listed.
            // Open question 2 in DATABASE_SCHEMA.md: % of FOB, per piece, per
            // shipment? Kept free-text until the client answers rather than
            // guessing an enum that then needs migrating.
            $table->string('commission_basis', 60)->nullable();

            // Not on the sheet. Commission is paid out to these people, so
            // there has to be somewhere to record who and where.
            $table->string('contact_person', 120)->nullable();
            $table->string('email', 150)->nullable();
            $table->string('mobile', 30)->nullable();
            $table->string('address', 255)->nullable();
            $table->string('city', 80)->nullable();
            $table->string('state', 80)->nullable();
            $table->foreignId('country_id')->nullable()->constrained()->nullOnDelete();
            $table->string('pincode', 20)->nullable();
            $table->string('bank_name', 120)->nullable();
            $table->string('account_number', 40)->nullable();
            $table->string('ifsc_code', 20)->nullable();

            $table->enum('status', ['active', 'inactive'])->default('active');
            $table->text('remarks')->nullable();

            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();
            $table->softDeletes();

            $table->index('status');
        });

        /*
         * Agent sheet col A: "drop down menu with a supplier side, buyer side
         * and jobber side".
         *
         * Three values, not two — the client's own master separates jobber from
         * supplier. A row per side rather than an enum column on `agents`,
         * because one agent can work both sides.
         */
        Schema::create('agent_sides', function (Blueprint $table) {
            $table->id();
            $table->foreignId('agent_id')->constrained()->cascadeOnDelete();
            $table->enum('side', ['buyer', 'supplier', 'jobber']);
            $table->timestamps();

            $table->unique(['agent_id', 'side']);
            // The Buyer form's agent dropdown filters on this.
            $table->index('side');
        });

        /*
         * Agent sheet col D: "drop down menu connected to the category master.
         * allow multiple choice and add a search bar".
         */
        Schema::create('agent_category', function (Blueprint $table) {
            $table->id();
            $table->foreignId('agent_id')->constrained()->cascadeOnDelete();
            $table->foreignId('category_id')->constrained()->cascadeOnDelete();

            $table->unique(['agent_id', 'category_id']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('agent_category');
        Schema::dropIfExists('agent_sides');
        Schema::dropIfExists('agents');
    }
};
