<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Auto-generated display codes and document numbers.
 *
 * Category sheet col A says "autogenerated" — CAT001, CAT002. Later modules
 * need the same thing with a financial-year prefix (GT/PO/2026-27/001), so the
 * generator is a table rather than a max(id)+1 lookup baked into one model.
 *
 * NumberSeriesService takes a row lock when it increments. Without it, two
 * users saving a category in the same second both read current_number = 4 and
 * both write CAT005.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('number_series', function (Blueprint $table) {
            $table->id();
            $table->string('module', 40);                        // category, product, buyer, po
            $table->string('prefix', 20)->default('');           // CAT, GT/PO/
            $table->string('financial_year', 10)->nullable();    // 2026-27; null when not year-scoped
            $table->unsignedBigInteger('current_number')->default(0);
            $table->unsignedTinyInteger('padding')->default(3);  // 3 -> 001
            $table->boolean('reset_yearly')->default(false);
            $table->timestamps();

            // One live counter per module per year. Two rows for the same
            // module would hand out duplicate codes.
            $table->unique(['module', 'financial_year']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('number_series');
    }
};
