<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Supplier master — Supplier Master sheet, DATABASE_SCHEMA.md §5.
 *
 * | Col | Field              | Sheet note                                                        |
 * |-----|--------------------|-------------------------------------------------------------------|
 * | A   | display code       | "it should tell me if a certain code is used already"             |
 * | B   | Company Name       | textbox                                                           |
 * | C   | Name on bill       | textbox                                                           |
 * | D   | Supplier type      | "(composition) give option to add more in the future" -> lookup   |
 * | E   | GST Number         | "only if the registered option is chosen"                         |
 * | F   | Pan number         | textbox                                                           |
 * | G   | MSME Registration  | "to appear to put in the msme registration details"               |
 * | H   | name               | textbox — the primary contact                                     |
 * | I   | designation        | "search bar and option to add a new one in the future" -> lookup  |
 * | J   | Email              | textbox                                                           |
 * | K   | Mobile             | textbox                                                           |
 * | L   | other contact persons | "name, designation, phone number need to come again to be filled" |
 * | M–Q | Address, City, State, Country, PIN Code | textboxes                                |
 * | R   | Product Category   | "drop down with a search bar menu, allow multiple to be chosen"   |
 * | S   | discount %         | "maximum 2 characters allowed"                                    |
 * | T   | Credit terms       | "maximum 3 characters allowed"                                    |
 * | U–W | bank name, account number, ifsc code | textboxes                                   |
 * | X   | Agent              | "of supplier side selected in agent master should show here"      |
 * | Y   | agent comm         | header only, no widget note                                       |
 * | Z   | Status             | "options to choose"                                               |
 * | AA  | Remarks            | textbox                                                           |
 *
 * Four deliberate departures from the sheet's own annotations, each with the
 * same justification as the equivalent call on the Buyer master:
 *
 * 1. `party_type`. Not on the sheet at all — it comes from DATABASE_SCHEMA.md
 *    §5, which establishes that Jobber and Supplier are two party types sharing
 *    one table. A PO, a purchase bill and a payment all go to either, so
 *    splitting the table would push a polymorphic party_type/party_id pair onto
 *    every downstream table and lose the foreign key. One table, one column,
 *    and the two screens are a filter on it.
 *
 * 2. Cols N, O, P (City / State / Country) are foreign keys although the sheet
 *    draws them as textboxes. Same reasoning as the Buyer master: these cascade
 *    on the form, and a dependent dropdown needs a parent to hang off.
 *    GeoController already exists and says in its own docblock that the
 *    Supplier form would reuse it.
 *
 * 3. Col R is headed "Product Category" and the note says "connect from product
 *    master". It links to `categories`, not `products` — the client's own
 *    example values are "Men's Shirts" and "Men's Bottoms", which are Category
 *    rows, and Jobber Q1 is explicit: "We link job worker to the category of
 *    product. And for trading we link 1/2 product categories to one supplier."
 *
 * 4. Cols H–K (the primary contact) are stored as a `supplier_contacts` row
 *    rather than four columns here, so that col L's extra people and the person
 *    on the main form are one list. Anything downstream that has to mail a
 *    supplier reads one table instead of a column set plus a table.
 *
 * The jobwork columns (`we_supply_material`, `requires_sample_approval`,
 * `default_delivery_mode`) are likewise not on the sheet. They are §5's
 * "fields that apply to one type only" table, and Material Issue cannot be
 * built without them. They are nullable/defaulted and only shown when the party
 * does jobwork.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('suppliers', function (Blueprint $table) {
            $table->id();

            // Col A. The unique index is what enforces "already used"; the live
            // check on the form is a convenience on top of it. Typed rather
            // than autogenerated, same as Buyer and Agent.
            $table->string('display_code', 5)->unique();

            /*
             * Not on the sheet — see the class docblock. `both` covers one
             * company used for jobwork on some categories and trading on
             * others, which is one row rather than two records carrying the
             * same GST number.
             */
            $table->enum('party_type', ['supplier', 'jobber', 'both'])->default('supplier');

            // Cols B, C
            $table->string('company_name', 200);
            $table->string('name_on_bill', 200)->nullable();

            // Cols D, E, F
            $table->foreignId('supplier_type_id')->nullable()->constrained()->nullOnDelete();
            $table->string('gst_number', 15)->nullable();
            $table->string('pan_number', 10)->nullable();

            /*
             * Col G. Two columns rather than one nullable string: "is this
             * supplier MSME" is a question the buyer-side payment rules ask
             * (MSME dues carry a statutory 45-day limit), and a registration
             * number that happens to be blank is not the same answer as "no".
             */
            $table->boolean('is_msme')->default(false);
            $table->string('msme_registration_no', 40)->nullable();

            // Cols M–Q. City/State/Country are FKs — see the class docblock.
            $table->string('address', 255)->nullable();
            $table->foreignId('country_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('state_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('city_id')->nullable()->constrained()->nullOnDelete();
            $table->string('pincode', 20)->nullable();

            /*
             * Col S — "maximum 2 characters allowed", so 0-99. decimal rather
             * than integer because the markup formula in §5b divides by it and
             * a half-percent discount is a normal thing to negotiate.
             */
            $table->decimal('discount_percent', 4, 2)->nullable();

            /*
             * Col T — "maximum 3 characters allowed", so 0-999 days. Stored as
             * a number, not the sheet's "45 Days" string, because the payment
             * due date is computed from it. 0 is meaningful for a jobber:
             * §5 records that jobbers "all take payment on dispatch".
             */
            $table->smallInteger('credit_days')->unsigned()->nullable();

            // Cols U–W
            $table->string('bank_name', 120)->nullable();
            $table->string('account_number', 40)->nullable();
            $table->string('ifsc_code', 11)->nullable();

            // Col X — nullable; not every supplier comes through an agent.
            $table->foreignId('agent_id')->nullable()->constrained()->nullOnDelete();

            /*
             * Col Y. Split into type + value for the same reason as the buyer's
             * col P: the Agent Commission screen in Accounts cannot settle
             * against a string that might be "2%" or might be "2 INR per piece".
             */
            $table->enum('agent_commission_type', ['percent', 'amount'])->nullable();
            $table->decimal('agent_commission_value', 12, 4)->nullable();

            /*
             * Jobwork-only, from DATABASE_SCHEMA.md §5. Not on the sheet.
             *
             * `we_supply_material` is what switches the Material Issue module on
             * for this party — Q5, "we generally supply everything".
             * `requires_sample_approval` blocks PO creation until a sample is
             * approved. `default_delivery_mode` is Q13: jobbers usually ship
             * direct to port, trading goods come to the office to be repacked.
             */
            $table->boolean('we_supply_material')->default(false);
            $table->boolean('requires_sample_approval')->default(false);
            $table->enum('default_delivery_mode', ['direct_to_port', 'to_office', 'to_warehouse'])
                ->default('to_office');

            // Cols Z, AA
            $table->enum('status', ['active', 'inactive'])->default('active');
            $table->text('remarks')->nullable();

            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();
            $table->softDeletes();

            // The Supplier and Jobber screens are each a filter on party_type,
            // and both then filter on status.
            $table->index(['party_type', 'status']);
            $table->index('company_name');
        });

        /*
         * Col R. restrictOnDelete on category_id, matching products and buyers:
         * a category a supplier is registered against cannot be deleted out
         * from under it. CategoryService::canDelete() answers with a sentence
         * before the database has to answer with an error.
         */
        Schema::create('supplier_category', function (Blueprint $table) {
            $table->id();
            $table->foreignId('supplier_id')->constrained()->cascadeOnDelete();
            $table->foreignId('category_id')->constrained()->restrictOnDelete();

            $table->unique(['supplier_id', 'category_id']);
        });

        /*
         * Cols H–K and L in one table — see point 4 in the class docblock.
         *
         * `is_primary` marks the person from the main form. It is not a unique
         * index: enforcing "exactly one primary" in the schema would make the
         * service rewrite rows in a specific order to avoid tripping it mid-
         * transaction, and SupplierService writes the primary first by
         * construction anyway.
         */
        Schema::create('supplier_contacts', function (Blueprint $table) {
            $table->id();
            $table->foreignId('supplier_id')->constrained()->cascadeOnDelete();
            $table->string('name', 120);
            $table->foreignId('designation_id')->nullable()->constrained()->nullOnDelete();
            $table->string('mobile', 30)->nullable();
            $table->string('email', 150)->nullable();
            $table->boolean('is_primary')->default(false);
            $table->timestamps();

            $table->index(['supplier_id', 'is_primary']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('supplier_contacts');
        Schema::dropIfExists('supplier_category');
        Schema::dropIfExists('suppliers');
    }
};
