<?php

namespace App\Models;

use App\Models\Concerns\Filterable;
use App\Models\Concerns\HasAuditColumns;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Agent master — Agent Master sheet.
 *
 * The screen is a later phase. This model exists now because the Buyer form's
 * agent dropdown is filtered by side, and that filter needs real tables behind
 * it. See the 000700 migration.
 *
 * Unlike Category and Product, `display_code` IS fillable: the sheet has the
 * user type it ("max 5 characters, it should tell me if a certain code is used
 * already"), so there is no autogenerated code for a crafted POST to overwrite.
 */
class Agent extends Model
{
    use Filterable, HasAuditColumns, SoftDeletes;

    /** The three sides an agent can work, per Agent sheet col A. */
    public const SIDES = [
        'buyer'    => 'Buyer side',
        'supplier' => 'Supplier side',
        'jobber'   => 'Jobber side',
    ];

    /**
     * @var list<string>
     */
    protected $fillable = [
        'display_code',
        'name',
        'commission_basis',
        'contact_person',
        'email',
        'mobile',
        'address',
        'city',
        'state',
        'country_id',
        'pincode',
        'bank_name',
        'account_number',
        'ifsc_code',
        'status',
        'remarks',
    ];

    /*
    |--------------------------------------------------------------------------
    | Relationships
    |--------------------------------------------------------------------------
    */

    public function sides(): HasMany
    {
        return $this->hasMany(AgentSide::class);
    }

    public function categories(): BelongsToMany
    {
        // No withTimestamps() — the pivot has none. See the 000700 migration.
        return $this->belongsToMany(Category::class, 'agent_category');
    }

    public function country(): BelongsTo
    {
        return $this->belongsTo(Country::class);
    }

    public function buyers(): HasMany
    {
        return $this->hasMany(Buyer::class);
    }

    /*
    |--------------------------------------------------------------------------
    | Scopes
    |--------------------------------------------------------------------------
    */

    /**
     * Buyer sheet col O and Supplier col X: "only those which are a part of
     * buyer side / supplier side selected in agent master should show here".
     *
     * One scope, three call sites — the Buyer, Supplier and Jobber forms.
     */
    public function scopeOnSide(Builder $query, string $side): Builder
    {
        return $query->whereHas('sides', fn (Builder $q) => $q->where('side', $side));
    }

    /*
    |--------------------------------------------------------------------------
    | Filtering
    |--------------------------------------------------------------------------
    */

    /**
     * @return array<int, string>
     */
    public function searchable(): array
    {
        return ['display_code', 'name', 'contact_person', 'email'];
    }

    /**
     * @return array<int, string>
     */
    public function sortable(): array
    {
        return ['id', 'display_code', 'name', 'status', 'created_at'];
    }

    /** "David (AG01)" — the code disambiguates two agents with the same name. */
    protected function label(): Attribute
    {
        return Attribute::get(fn () => "{$this->name} ({$this->display_code})");
    }
}
