<?php

namespace App\Models;

use App\Models\Concerns\Filterable;
use App\Models\Concerns\HasAuditColumns;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use Filterable, HasAuditColumns, SoftDeletes;

    /**
     * `code` is deliberately absent — it is assigned by NumberSeriesService,
     * never accepted from the request. Leaving it fillable would let a crafted
     * POST overwrite an autogenerated code.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'description',
        'po_format_id',
        'status',
        'remarks',
    ];

    /*
    |--------------------------------------------------------------------------
    | Relationships
    |--------------------------------------------------------------------------
    */

    public function poFormat(): BelongsTo
    {
        return $this->belongsTo(DocumentFormat::class, 'po_format_id');
    }

    public function products(): HasMany
    {
        return $this->hasMany(Product::class);
    }

    /*
    |--------------------------------------------------------------------------
    | Filtering
    |--------------------------------------------------------------------------
    */

    /**
     * @return array<int, string>
     */
    public function searchable(): array
    {
        return ['code', 'name', 'remarks'];
    }

    /**
     * @return array<int, string>
     */
    public function sortable(): array
    {
        return ['id', 'code', 'name', 'status', 'created_at'];
    }
}
