<?php

namespace App\Models;

use App\Models\Concerns\Filterable;
use App\Models\Concerns\HasAuditColumns;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Inquiry — Order Flow's entry point. A buyer asks, we cost it against an
 * Order Format's item table, and confirmed lines convert to an Order
 * Confirmation (not yet built — see convertToOc()).
 *
 * `inquiry_no` and `financial_year` are deliberately absent from $fillable:
 * both are assigned by InquiryService from NumberSeriesService, same
 * treatment Category::$code gets — there is no autogenerated value here for a
 * crafted POST to overwrite.
 */
class Inquiry extends Model
{
    use Filterable, HasAuditColumns, SoftDeletes;

    /**
     * Shared by the header and every item row — an item can sit at an
     * earlier or later stage than the inquiry it belongs to (some lines
     * confirmed, some still being quoted, some lost).
     *
     * @var array<string, string>
     */
    public const STATUSES = [
        'draft'           => 'Draft',
        'price_working'   => 'Price Working',
        'quote_sent'      => 'Quote Sent',
        'confirmed'       => 'Confirmed',
        'converted_to_oc' => 'Converted to OC',
        'lost'            => 'Lost',
    ];

    /**
     * Bootstrap-badge colour per status, for the six-state pill the list and
     * show screens use instead of the boolean x-ui.status-badge.
     *
     * @var array<string, string>
     */
    public const STATUS_COLORS = [
        'draft'           => 'secondary',
        'price_working'   => 'info',
        'quote_sent'      => 'primary',
        'confirmed'       => 'success',
        'converted_to_oc' => 'success',
        'lost'            => 'danger',
    ];

    /**
     * @var list<string>
     */
    protected $fillable = [
        'inquiry_date',
        'buyer_ref',
        'source_id',
        'buyer_id',
        'category_id',
        'document_format_id',
        'agent_id',
        'agent_commission_type',
        'agent_commission_value',
        'currency_id',
        'exchange_rate',
        'expected_shipment_date',
        'delivery_details',
        'packing_details',
        'remarks',
        'status',
        'converted_at',
    ];

    protected function casts(): array
    {
        return [
            'inquiry_date'            => 'date',
            'expected_shipment_date'  => 'date',
            'converted_at'            => 'datetime',
            'agent_commission_value'  => 'decimal:4',
            'exchange_rate'           => 'decimal:4',
        ];
    }

    /*
    |--------------------------------------------------------------------------
    | Relationships
    |--------------------------------------------------------------------------
    */

    public function buyer(): BelongsTo
    {
        return $this->belongsTo(Buyer::class);
    }

    /** Change request #8 — quick-add lookup, replacing the fixed SOURCES list. */
    public function source(): BelongsTo
    {
        return $this->belongsTo(InquirySource::class);
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /** Bound to the DocumentFormat model — "Order Format" everywhere in the UI. */
    public function format(): BelongsTo
    {
        return $this->belongsTo(DocumentFormat::class, 'document_format_id');
    }

    public function agent(): BelongsTo
    {
        return $this->belongsTo(Agent::class);
    }

    public function currency(): BelongsTo
    {
        return $this->belongsTo(Currency::class);
    }

    public function items(): HasMany
    {
        return $this->hasMany(InquiryItem::class)->orderBy('sort_order');
    }

    public function followUps(): HasMany
    {
        return $this->hasMany(InquiryFollowUp::class)->orderByDesc('follow_up_date')->orderByDesc('id');
    }

    /*
    |--------------------------------------------------------------------------
    | Derived
    |--------------------------------------------------------------------------
    */

    public function statusLabel(): string
    {
        return self::STATUSES[$this->status] ?? $this->status;
    }

    public function sourceLabel(): string
    {
        return $this->source?->name ?? '—';
    }

    public function statusColor(): string
    {
        return self::STATUS_COLORS[$this->status] ?? 'secondary';
    }

    /** Sum of every item's amount — computed, not stored on the header. */
    public function totalAmount(): float
    {
        return (float) $this->items->sum('amount');
    }

    /*
    |--------------------------------------------------------------------------
    | Filtering
    |--------------------------------------------------------------------------
    */

    /**
     * @return array<int, string>
     */
    public function searchable(): array
    {
        return ['inquiry_no', 'buyer_ref', 'remarks'];
    }

    /**
     * @return array<int, string>
     */
    public function sortable(): array
    {
        return ['id', 'inquiry_no', 'inquiry_date', 'status', 'created_at'];
    }

    /**
     * Reaches into the buyer, same shape as Buyer::scopeSearch() reaching
     * into city/state — "find the inquiry" usually means "find the buyer".
     */
    public function scopeSearch(Builder $query, ?string $term): Builder
    {
        if (blank($term)) {
            return $query;
        }

        return $query->where(function (Builder $q) use ($term) {
            foreach ($this->searchable() as $column) {
                $q->orWhere($column, 'like', "%{$term}%");
            }

            $q->orWhereHas('buyer', fn (Builder $b) => $b
                ->where('company_name', 'like', "%{$term}%")
                ->orWhere('display_code', 'like', "%{$term}%"));
        });
    }

    /**
     * The trait's default only knows active/inactive — Inquiry has six
     * pipeline stages instead.
     */
    public function scopeStatus(Builder $query, ?string $status): Builder
    {
        if (blank($status) || ! array_key_exists($status, self::STATUSES)) {
            return $query;
        }

        return $query->where('status', $status);
    }
}
