<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Counter behind every autogenerated code. Written only through
 * NumberSeriesService, which holds a row lock while it increments.
 */
class NumberSeries extends Model
{
    protected $table = 'number_series';

    protected $fillable = [
        'module',
        'prefix',
        'financial_year',
        'current_number',
        'padding',
        'reset_yearly',
    ];

    protected function casts(): array
    {
        return [
            'current_number' => 'integer',
            'padding'        => 'integer',
            'reset_yearly'   => 'boolean',
        ];
    }
}
