<?php

namespace App\Models;

use App\Models\Concerns\Filterable;
use App\Models\Concerns\HasAuditColumns;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Supplier master — Supplier Master sheet. Column mapping is in the 000200
 * migration.
 *
 * `display_code` IS fillable, like Buyer::$display_code and unlike
 * Category::$code. The sheet has the user type it and asks for a duplicate
 * warning, so there is no autogenerated value for a crafted POST to overwrite —
 * the unique index is the guard instead.
 */
class Supplier extends Model
{
    use Filterable, HasAuditColumns, SoftDeletes;

    /**
     * DATABASE_SCHEMA.md §5. Jobber and Supplier are two party types sharing
     * this table, not two words for the same thing — what we buy, who supplies
     * the raw material, the payment terms and where the goods go all differ.
     *
     * @var array<string, string>
     */
    public const PARTY_TYPES = [
        'supplier' => 'Supplier (trading — finished goods)',
        'jobber'   => 'Jobber (jobwork — we supply the material)',
        'both'     => 'Both',
    ];

    /** Col Q13 — where the goods go when a PO against this party is produced. */
    public const DELIVERY_MODES = [
        'to_office'      => 'To office (repacked here)',
        'direct_to_port' => 'Direct to port',
        'to_warehouse'   => 'To warehouse',
    ];

    /**
     * Which side of the Agent master this party's agent may come from.
     *
     * Sheet col X says "of supplier side selected in agent master should show
     * here". That is the sheet for a trading supplier; a jobber's agent is a
     * jobber-side agent, and Agent::TYPES already separates the three. Read by
     * both the dropdown and the validation rule, so the filter the user sees
     * and the rule that enforces it cannot drift apart.
     *
     * @var array<string, array<int, string>>
     */
    public const AGENT_SIDES = [
        'supplier' => ['supplier'],
        'jobber'   => ['jobber'],
        'both'     => ['supplier', 'jobber'],
    ];

    /**
     * @var list<string>
     */
    protected $fillable = [
        'display_code',
        'party_type',
        'company_name',
        'name_on_bill',
        'supplier_type_id',
        'gst_number',
        'pan_number',
        'is_msme',
        'msme_registration_no',
        'address',
        'country_id',
        'state_id',
        'city_id',
        'pincode',
        'discount_percent',
        'credit_days',
        'bank_name',
        'account_number',
        'ifsc_code',
        'agent_id',
        'agent_commission_type',
        'agent_commission_value',
        'we_supply_material',
        'requires_sample_approval',
        'default_delivery_mode',
        'client_details',
        'status',
        'remarks',
        'comments',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'is_msme'                  => 'boolean',
            'we_supply_material'       => 'boolean',
            'requires_sample_approval' => 'boolean',
            'discount_percent'         => 'decimal:2',
            'agent_commission_value'   => 'decimal:4',
            'credit_days'              => 'integer',
        ];
    }

    /*
    |--------------------------------------------------------------------------
    | Relationships
    |--------------------------------------------------------------------------
    */

    /** Col R — "allow multiple to be chosen". Categories, not products; see the migration. */
    public function categories(): BelongsToMany
    {
        // No withTimestamps() — the pivot has none.
        return $this->belongsToMany(Category::class, 'supplier_category');
    }

    /** Change request #1 — a jobber can be linked to more than one product, same as categories above. */
    public function products(): BelongsToMany
    {
        return $this->belongsToMany(Product::class, 'supplier_product');
    }

    /**
     * Jobwork's "client" — who the finished goods are ultimately for. Was a
     * free-text `client_name` column; now linked to the Buyer master so the
     * jobber can point at one or more real buyer records instead of a typed
     * name that could drift from the actual buyer.
     */
    public function buyers(): BelongsToMany
    {
        return $this->belongsToMany(Buyer::class, 'supplier_buyer');
    }

    /**
     * Cols H–K and L. Primary first, then the extras in the order they were
     * entered — ordered here so no caller has to remember to sort.
     */
    public function contacts(): HasMany
    {
        return $this->hasMany(SupplierContact::class)
            ->orderByDesc('is_primary')
            ->orderBy('id');
    }

    /** Cols H–K on their own — the person the main form asks for. */
    public function primaryContact(): HasOne
    {
        return $this->hasOne(SupplierContact::class)->where('is_primary', true);
    }

    public function supplierType(): BelongsTo
    {
        return $this->belongsTo(SupplierType::class);
    }

    public function country(): BelongsTo
    {
        return $this->belongsTo(Country::class);
    }

    public function state(): BelongsTo
    {
        return $this->belongsTo(State::class);
    }

    public function city(): BelongsTo
    {
        return $this->belongsTo(City::class);
    }

    public function agent(): BelongsTo
    {
        return $this->belongsTo(Agent::class);
    }

    /*
    |--------------------------------------------------------------------------
    | Scopes
    |--------------------------------------------------------------------------
    */

    /**
     * One party type's rows, including those marked `both`.
     *
     * This is what makes two screens out of one table: the Supplier screen
     * calls ofParty('supplier'), the Jobber screen ofParty('jobber'), and a
     * company that does both work appears on each without being entered twice.
     *
     * @param  \Illuminate\Database\Eloquent\Builder<static>  $query
     * @return \Illuminate\Database\Eloquent\Builder<static>
     */
    public function scopeOfParty(Builder $query, ?string $partyType): Builder
    {
        if (blank($partyType) || ! array_key_exists($partyType, self::PARTY_TYPES)) {
            return $query;
        }

        return $partyType === 'both'
            ? $query->where('party_type', 'both')
            : $query->whereIn('party_type', [$partyType, 'both']);
    }

    /*
    |--------------------------------------------------------------------------
    | Accessors
    |--------------------------------------------------------------------------
    */

    /** Whether this party does jobwork — drives the jobwork-only fields on the form. */
    protected function doesJobwork(): Attribute
    {
        return Attribute::get(fn () => in_array($this->party_type, ['jobber', 'both'], true));
    }

    /**
     * Col Y rendered for display — "2.5%" or "1.5 INR".
     *
     * The type and the value are stored separately so settlement maths never
     * parses a label; this is the label, built back from them. Supplier-side
     * commission is always in INR — a jobber and a trading supplier are both
     * domestic, unlike the buyer's, which follows the buyer's own currency.
     */
    protected function agentCommissionLabel(): Attribute
    {
        return Attribute::get(function () {
            if (blank($this->agent_commission_value) || blank($this->agent_commission_type)) {
                return null;
            }

            $value = rtrim(rtrim(number_format((float) $this->agent_commission_value, 4, '.', ''), '0'), '.');

            return $this->agent_commission_type === 'percent' ? "{$value}%" : "{$value} INR";
        });
    }

    /** Col T rendered the way the sheet writes it — "45 Days", or "On dispatch" for 0. */
    protected function creditTermsLabel(): Attribute
    {
        return Attribute::get(function () {
            if ($this->credit_days === null) {
                return null;
            }

            return $this->credit_days === 0 ? 'On dispatch' : "{$this->credit_days} Days";
        });
    }

    /*
    |--------------------------------------------------------------------------
    | Filtering
    |--------------------------------------------------------------------------
    */

    /**
     * @return array<int, string>
     */
    public function searchable(): array
    {
        return ['display_code', 'company_name', 'name_on_bill', 'gst_number', 'pan_number'];
    }

    /**
     * City is not sortable — it lives on a related table and Filterable::scopeSort()
     * puts the column straight into ORDER BY without a join. Same call as Buyer.
     *
     * @return array<int, string>
     */
    public function sortable(): array
    {
        return ['id', 'display_code', 'company_name', 'credit_days', 'status', 'created_at'];
    }

    /**
     * Filterable::scopeSearch only knows about columns on this table. The list
     * screen offers city and the contact person, both of which live elsewhere,
     * so they are folded into the same OR group rather than the search box
     * quietly being narrower than the column it sits above. Same shape as
     * Buyer::scopeSearch().
     */
    public function scopeSearch(Builder $query, ?string $term): Builder
    {
        if (blank($term)) {
            return $query;
        }

        return $query->where(function (Builder $q) use ($term) {
            foreach ($this->searchable() as $column) {
                $q->orWhere($column, 'like', "%{$term}%");
            }

            $q->orWhereHas('city', fn (Builder $c) => $c->where('name', 'like', "%{$term}%"));
            $q->orWhereHas('state', fn (Builder $s) => $s->where('name', 'like', "%{$term}%"));
            $q->orWhereHas('contacts', fn (Builder $c) => $c->where('name', 'like', "%{$term}%"));
        });
    }

    /** "Sri Garments (SUP01)" — for dropdowns on the PO and rate screens. */
    protected function label(): Attribute
    {
        return Attribute::get(fn () => "{$this->company_name} ({$this->display_code})");
    }
}
